### ISSUE TITLE
Can't close messages box

### ISSUE THREAD

**Issue by Varunram** [Musicoin/forum#6]
I can't seem to close the messages box after replying to a message, it'd be helpful if there was a button to do that. Thanks!

<img width="1280" alt="screen shot 2018-01-07 at 5 38 42 pm" src="https://user-images.githubusercontent.com/18598959/34649351-77c80212-f3d3-11e7-9bc3-e8efd92a63cb.png">

**Comment by hayrullahcansu** [comment]
this issue fixed forum-side
![image](https://user-images.githubusercontent.com/10001588/34650462-cf6b53ee-f3d2-11e7-896f-5bd3f2c2e6d2.png)
