### ISSUE TITLE
Font size / broken Link

### ISSUE THREAD

**Issue by Archimedes1618** [Musicoin/forum#8]
Something changed the Font size, broke the UI and made some Links inaccessible
![screenshot-2018-2-4_music_forum_let_s_rock](https://user-images.githubusercontent.com/36302281/36032373-13ecff1e-0dae-11e8-9908-dac22bc6f17a.png)
![musicoinwebsite](https://user-images.githubusercontent.com/36302281/36032375-1408f2dc-0dae-11e8-83aa-5c07360cef78.png)

see https://github.com/NodeBB/NodeBB/commit/6533c664d6fa38749315dac0338343fd4ad873cb

might be related

**Comment by Varunram** [comment]
Thanks for the bug report! We were developing a new style for the forum due to the above mentioned bugs and things should work fine now.

**Comment by Archimedes1618** [comment]
![emptyspace](https://user-images.githubusercontent.com/36302281/36040274-43d99a68-0dc5-11e8-8288-116fac37c537.png)


UI is fine for the most part now. Menue and everything else seems to be in place beside that empty space and the right sidebar

**Comment by Varunram** [comment]
Oh, that's weird. I tested and it looked fine on a HD screen. What resolution are you using?

**Comment by Archimedes1618** [comment]
tested on: 22" lcd 1680x1050 msedge , 24"lcd 16:9 1920x1080 firefox, 29" lcd 21:9 2560x1080 firefox and ms edge. same look on all machines
